### PR TITLE
Regen and update patches

### PR DESCRIPTION
**Pull request by klabit87**
Updated to most recent.

### CODE REVIEW

**Comment by phhusson** [comment]
Just as a FYI, there is no need to regen by yourself, it's generated automatically at every release:
https://github.com/phhusson/treble_experimentations/releases/download/v114/patches.zip

**Comment by klabit87** [comment]
I can't believe I didn't see that before. Thanks!

**Comment by phhusson** [comment]
It would be nice to update build-dakkar to download patches from there
instead than here if you have the time :-)

**Comment by klabit87** [comment]
Good point. I will get to that next chance I get.

**Pull request merged**
